[FEAT] 페이지뷰 구현, 추천탭 UI 구현
SIDETEAM001/side-ios pull request #75
Opened 2023-12-04 05:05 UTC by duthd3

## [#70] [FEAT] : 페이지뷰 구현, 추천 탭 UI 구현

## 🌱 작업한 내용

- 추천, 자기개발, 취미 페이지뷰 구현
- 추천 탭 UI 구현(스크롤 뷰, 스택뷰 등)

## 🌱 PR Point

- SceneDelegate 실수로 원상태로 복구 못하고 push 함.

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 홈화면 추천 탭 | ![simulator_screenshot_D9D2B28F-8963-4A01-855F-7FE7B22A1192](https://github.com/SIDETEAM001/side-ios/assets/79510152/54c16a43-4a7d-49a2-8972-abdeb1369fed) |

## 📮 관련 이슈

- 없음.

2023-12-05 13:35 UTC, dumok-nim commented
@duthd3 저기 "취미를 찾으러가볼까요?" 뷰의 leading, trailing 패딩값이 좀 커보입니다.
디자인상에는 아래 "단기 모임 추천" 레이블과 align되어있는데, 코드 확인한번 해주세요~!

2023-12-05 13:36 UTC, dumok-nim requested changes

2023-12-05 13:36 UTC, dumok-nim commented on Projects/Feature/Home/Sources/HomeViewController.swift
> +
불필요한 공백은 conflict의 주된 요인입니다!
정리 부탁드립니다ㅎㅎ

2023-12-05 13:36 UTC, dumok-nim commented on Projects/Feature/Home/Sources/HomeViewController.swift
> +    @objc private func didChangeValue(segment:UISegmentedControl) {
```suggestion
    @objc private func didChangeValue(segment: UISegmentedControl) {
```

2023-12-05 13:36 UTC, dumok-nim commented on Projects/Feature/Home/Sources/HomeViewController.swift
> +        }else if segment.selectedSegmentIndex == 1{
```suggestion
        } else if segment.selectedSegmentIndex == 1 {
```

2023-12-19 09:48 UTC, duthd3 commented on Projects/Feature/Home/Sources/HomeViewController.swift
> +
수정완료했습니다

2023-12-19 12:40 UTC, dumok-nim commented on Projects/Feature/Home/Sources/HomeViewController.swift
> +        }else if segment.selectedSegmentIndex == 1{
@duthd3 ㅠㅠ 1 뒤에도 띄어씌기 해야하는데 일단 제가 고쳐서 넘기겠습니다

2023-12-19 12:41 UTC, merged