[#74][FEAT] 채팅방 화면 레이아웃 그리기
SIDETEAM001/side-ios pull request #98
Opened 2023-12-27 08:54 UTC by kms0524

## [#74] [FEAT] : 채팅방 화면 레이아웃 그리기

## 🌱 작업한 내용
- 채팅탭바의 최초화면 구현
- 채팅방 내부 화면 구현
- 공지, 일정 화면 구현
- develop과 rebase and merge 예정

## 📮 관련 이슈
- Resolved: #74

2023-12-27 19:28 UTC, dumok-nim requested changes
수고하셨습니다~!
공백과 관련된 부분은 컨벤션이 지켜지지 않았다고 추측되는 부분에 코멘트를 작성하였습니다.
혹시 컨벤션에 맞게 잘 작성된 경우라면 해당 conversation에 코멘트 남겨주세요!

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Interface/Sources/ConversationMockData.swift
> +public struct OthersConversationCellMockData {
OthersConversationCellMockData, FirstOthersConversationCellMockData
두 모델을 따로 사용하는 이유가 무었인가요?
아래 두 property들을 nil로 관리하면 혹시 문제가 발생할까요?
```swift
public var profileImage: UIImage
public var name: String
````

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Interface/Sources/MockUpNoticeModel.swift
> +
여기 공백 제거해서 컨벤션 맞춰주세요!

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Cell/FirstOthersConversationTableViewCell.swift
> +    var nameLabel: UILabel = {
상수가 아닌 변수로 선언한 이유가 있을까요?

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Chats/ChattingList/ChattingListViewController.swift
> +
공백을 제거하여 컨벤션을 맞춰주세요!

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Chats/ChattingList/ChattingListViewController.swift
> +            break
default문을 제외하고 `break`를 굳이 안넣어줘도될 것 같습니다.

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Chats/ChattingRoom/ChattingRoomSideMenuViewController.swift
> +        guard let view = touch.view else { return false }
이 조건문도 guard문에 포함시켜도 될거같은데 어떻게 생각하시나요?

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Chats/ChattingRoom/ChattingRoomViewController.swift
> +
공백을 제거하여 컨벤션을 맞춰주세요!

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Chats/ChattingRoom/ChattingRoomViewController.swift
> +
공백을 제거하여 컨벤션을 맞춰주세요!

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/Chats/ChattingRoom/ChattingRoomViewController.swift
> +
공백을 제거하여 컨벤션을 맞춰주세요!

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/NSV/NSVViewController.swift
> +            tableView.reloadData()
csae 0과 1이 동일하다면 하나로 합쳐도 될 것 같습니다.

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/NSV/NSVViewController.swift
> +        tableView.delegate = self
여기와 `setUp()` 함수에 아래 두 코드가 중복되어있는데 의도된 것인가요?

```swift
tableView.delegate = self
ableView.dataSource = self
```

2023-12-27 19:28 UTC, dumok-nim commented on Projects/Feature/Chat/Sources/NSV/NSVViewController.swift
> +        case 0:
0일떄도 break처리를 해줄 것이라면 
`case 0:` 을 제거하고, default문으로 빠지게 해도될 것같습니다.

혹은 switch를 사용하지 않고
`segmentedControl.selectedSegmentIndex == 1` 인경우에 대한 조건문으로 바꿔도 좋을 것 같습니다.

2023-12-28 04:53 UTC, duthd3 approved these changes

2023-12-28 04:53 UTC, duthd3 commented on Projects/App/Sources/Application/SceneDelegate.swift
> +        window?.backgroundColor = .white
K님 SceneDelegate 부분 원상태로 돌려 놓으라고 하셨던 것 같은데 수정 못 하신것 같아요

2023-12-28 05:13 UTC, pjs9797 approved these changes

2023-12-28 07:07 UTC, fhwmqkfl approved these changes

2023-12-28 07:39 UTC, kms0524 commented on Projects/Feature/Chat/Interface/Sources/ConversationMockData.swift
> +public struct OthersConversationCellMockData {
아 그부분은 놓친거같네요 나중에 하나로 합치는걸로 하겠습니다

2023-12-28 07:48 UTC, kms0524 commented on Projects/Feature/Chat/Sources/Cell/FirstOthersConversationTableViewCell.swift
> +    var nameLabel: UILabel = {
이유는 딱히 없고 제 코드스타일이 ui관련된 부분은 항상 변경여지가 있기때문에 변수로 선언해왔습니다

2023-12-28 07:49 UTC, kms0524 commented on Projects/Feature/Chat/Sources/Chats/ChattingList/ChattingListViewController.swift
> +
😗

2023-12-28 07:49 UTC, kms0524 commented on Projects/Feature/Chat/Sources/Chats/ChattingRoom/ChattingRoomViewController.swift
> +
😗😗

2023-12-28 07:49 UTC, kms0524 commented on Projects/Feature/Chat/Sources/Chats/ChattingRoom/ChattingRoomViewController.swift
> +
😗😗😗

2023-12-28 07:52 UTC, kms0524 commented on Projects/Feature/Chat/Sources/NSV/NSVViewController.swift
> +        tableView.delegate = self
아 이건 제가 놓친거같습니다. 중복코드 삭제하겠습니다

2023-12-28 07:55 UTC, kms0524 commented on Projects/Feature/Chat/Sources/NSV/NSVViewController.swift
> +        case 0:
0일때 다른뷰로 빠지게해야하는 코드가 작성되어야 하는데 이거는 네트워크 작업이 완료되어야 테스트 할수있는거라 아직 작성안해놨습니다!

2023-12-29 05:29 UTC, closed without merging